name: Train ViT Model

on:
  push:
    branches:
      - main
    paths:
      - 'train_vit.py'
      - 'utils/**'
      - 'requirements.txt'
      - '.github/workflows/train.yml'

jobs:
  train:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV


    - name: Run ViT training
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        python train_vit.py \
          --train_dir vit-data/train \
          --val_dir vit-data/val \
          --epochs 1 \
          --upload_to_s3 \
          --s3_bucket e-see-vit-model

    - name: Run YOLOv8 training
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        python train_yolov8.py \
          --data yolo-data/data.yaml \
          --epochs 1 \
          --upload_to_s3 \
          --s3_bucket e-see-vit-model
